### ISSUE TITLE
Registering does not send back a token

### ISSUE THREAD

**Issue by emyrTomos** [matthewkaras/api_v2#1]
If I get bounced from the full analysis page to the login page and register a new user I get issued an ID and username at which point the client side app bounces me back to the fullanalysis page. However the endpoints still return 401 and I am bounced back to the login page. If I enter the username and password I have just created I get success and am bounced back to the fullanalysis page, which then loads.

**Comment by timcowlishaw** [comment]
aha, so on registration we want to create a session too? sounds sensible. I'll get onto that!
